# 相当于脚本用途的一个声明
name: Release
# 触发脚本的事件  这里为发布release之后触发
on:
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          cd source/java
          bash build.sh
          cd polaris-specification
          mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Build and publish Python package
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
        run: |
          pip install grpcio-tools
          python source/python/build.py
          pip install --upgrade hatch
          hatch build
          hatch publish --no-prompt
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
